tap "homebrew/bundle"

# Newer versions of core utilities that aren't bundled with MacOS
brew "gcc"
brew "libressl"
brew "openssh"
brew "coreutils"
brew "git"
brew "gnupg"
brew "zsh"
brew "svn" # Needed for some fonts

cask "bruno"

cask "firefox"
