[tools]
lima = "latest"
colima = "latest"

[tools."aqua:docker/cli"]
version = "latest"

[tools."aqua:docker/compose"]
version = "latest"
postinstall = "ln -sf $MISE_TOOL_INSTALL_PATH/docker-cli-plugin-docker-compose $HOME/.docker/cli-plugins/docker-compose"

[tools."aqua:docker/buildx"]
version = "latest"
postinstall = "ln -sf $MISE_TOOL_INSTALL_PATH/docker-cli-plugin-docker-buildx $HOME/.docker/cli-plugins/docker-buildx"
