cask "iterm2"
cask "rectangle"
cask "keepingyouawake"
cask "notunes"

brew "mas"
mas "XCode", id: 497799835
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Horo - Timer for Menu Bar", id: 1437226581
